# java 8 위에서 스프링 부트 앱이 실행
FROM openjdk:8-jdk-alpine
WORKDIR /var/jenkins_home/workspace/deployment/backend
ARG JAR_FILE=build/libs/README-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
# 어플리케이션 실행 명령어 : java 실행 명령어
ENTRYPOINT ["java","-jar","/app.jar"]
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul


