# java 8 위에서 스프링 부트 앱이 실행
FROM openjdk:8-jdk-alpine AS build
WORKDIR /var/jenkins_home/workspace/deployment/backend
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x gradlew
RUN ["./gradlew", "clean", "bootJar"]
